ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
	$(MAIN_DIR)/travaux_pratiques/interco.kernel.qa/images/*.png \
	$(MAIN_DIR)/travaux_pratiques/interco.rawip.qa/images/*.png \
	$(MAIN_DIR)/travaux_pratiques/interco.ppp.qa/images/*.png \
	$(MAIN_DIR)/travaux_pratiques/interco.cs/images/*.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
