ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = $(MAIN_DIR)/travaux_pratiques/interco.ospf-frr.qa/files/*

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
