ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        ../../interco.ppp.qa/images/*.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
