ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
	$(wildcard $(MAIN_DIR)/travaux_pratiques/interco_05.ospf/files/*.conf)

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
