#!/bin/sh

# radvd main configuration file
radvd_conf="/etc/radvd.conf"

if [ -z "$(grep $IFACE $radvd_conf)" ]
then

# ULA network prefix
prefix=fd27:1684:e79b

# DNS resolver IPv6 address
ipv6_resolver=2001:db8:fe00:8175::1

# extract $IFACE number as network nibble
netnum=$(echo $IFACE | grep -o [0-9]*)

cat << EOF >> $radvd_conf

interface $IFACE
{
	AdvSendAdvert on;
	prefix $prefix:$netnum::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};

	RDNSS $ipv6_resolver
	{
	};
};
EOF

systemctl restart radvd

fi
