#!/bin/sh

# ULA network prefix
prefix=fd27:1684:e79b

# extract $IFACE number as network nibble
netnum=$(echo $IFACE | grep -o [0-9]*)

# compute ULA interface address
ula=$prefix:$netnum::1/64

ip -6 addr add $ula dev $IFACE
