ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        $(MAIN_DIR)/articles/inter-vlan-routing-openvswitch/images/ovs-vm.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules

