ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Liste des répertoires à traiter à partir de ce niveau
SUBDIRS = \
	images

# Type(s) de traitement
PROCESS = odp2xhtml

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
