ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        $(MAIN_DIR)/images/thumbs/thumb008.png \
        $(MAIN_DIR)/images/minus-button-32.png \
        $(MAIN_DIR)/images/plus-button-32.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
