ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        $(MAIN_DIR)/articles/modelisation/images/modelisation-osi.{png,svg} \
        $(MAIN_DIR)/travaux_pratiques/intro.analyse/images/wireshark-thumb.png \
        $(MAIN_DIR)/images/thumbs/thumb004.png \
        $(MAIN_DIR)/images/thumbs/thumb006.png \
        $(MAIN_DIR)/images/thumbs/thumb009.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
