ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = $(MAIN_DIR)/travaux_pratiques/sysadm-net.dns.qa/images/*.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
