ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        $(MAIN_DIR)/images/thumbs/thumb004.png \
        $(MAIN_DIR)/articles/modelisation/images/osi.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
