ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        $(MAIN_DIR)/presentations/os-arch-hints/images/kernel-network-subsystem.png

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
