ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = xml2xhtml xml2pdf

XML_FILES = tutoriel.securite.xml urls.xml

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
