ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = odp2xhtml

geometry = 1067x600
thumb-geometry = 267x150

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
