ifndef $(MAIN_DIR)
MAIN_DIR = $(HOME)/inetdoc
endif

# Type(s) de traitement
PROCESS = symlink

SYMLINKS = \
        $(MAIN_DIR)/guides/vm/files/startup.sh

all: $(PROCESS)

include $(MAIN_DIR)/common/Makefile.Rules
